### ISSUE TITLE
Modal windows issue, videoUrl is unsafe

### ISSUE THREAD

**Issue by lenkaswarna** [AWNICS/mm-ngx#61]
**Current behavior**

- By clicking on a video image on doctor modal window, 
- then it's going to a new modal window but the video is not running.

  
**Expected behavior**

- After clicking on given image the new modal window will open with a video, 
- by clicking on that video it will run.

**Minimal reproduction of the problem with instructions**

 chat.component.html:95 ERROR Error: unsafe value used in a resource URL context (see 
  http://g.co/ng/security#xss)
    at DomSanitizerImpl.sanitize (dom_sanitization_service.ts:209)

![Uploading bug.png…]
![bug](https://user-images.githubusercontent.com/30042620/37389617-0e29bcba-278b-11e8-8eb6-6be4b6e888a0.png)

**Comment by arun-awnics** [comment]
It is not a bug. Use angular's dom sanitizer technique to remove the error. It is a code flaw. Following is the link: [Angular DomSanitizer](https://angular.io/api/platform-browser/DomSanitizer)

**Comment by arun-awnics** [comment]
Closing issue because component is outdated and issue is irrelevant.
