### ISSUE TITLE
Modal window all components are not responsive

### ISSUE THREAD

**Issue by lenkaswarna** [AWNICS/mm-ngx#63]
**Current behavior**
   1.Status is coming top of the profile picture.
   2. Consult Now button and Collapse Button are overlapping in less width.
   3.Video modal is not responsive.
   4.Thumbnail is on left

**Expected behavior**
 1.Status should come at the left of the profile image.
 2.Consult Now button and Collapse should come on the different column without overlapping.
 3.Require responsive video modal
 4.Require Thumbnail on center

**Comment by arun-awnics** [comment]
Irrelevant issue. Closing the issue because this component is not being used. Can reopen if needed later.
