### ISSUE TITLE
Welcome message by Bot

### ISSUE THREAD

**Issue by niluroy** [AWNICS/mm-ngx#65]
[ ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
       Along with time stamp bot name is not displaying
![bug1](https://user-images.githubusercontent.com/30042604/37504232-ff245cec-2902-11e8-8ce8-815206cbe820.png)

**Expected behavior**
     Along with time stamp bot name should come

**Comment by arun-awnics** [comment]
Issue fixed.
