### ISSUE TITLE
Issue in div showing list of groups

### ISSUE THREAD

**Issue by niluroy** [AWNICS/mm-ngx#66]
[ ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
![image](https://user-images.githubusercontent.com/30042604/37504386-ff244abc-2903-11e8-829d-284b72ba2258.png)

**Expected behavior**
div showing list of groups and users online should not come over footer

**Comment by arun-awnics** [comment]
There is no issue with displaying groups list.
