### ISSUE TITLE
In doctor register form register button is not working.

### ISSUE THREAD

**Issue by lenkaswarna** [AWNICS/mm-ngx#67]
**Current behavior**
 By clicking on the register button, it's not registering doctor.

**Expected behavior**
   After clicking on register button it will create a doctor.

![screenshot 21](https://user-images.githubusercontent.com/30042620/37508233-38ce1c02-2918-11e8-8281-4b6d8747764d.png)

**Comment by arun-awnics** [comment]
#62 Fixed
